tasks:
  - name: Setup environment variables
    command: |
      source ./setup-env-variables.sh
      gp sync-done env-setup
  - name: Install AWS CLI
    command: |
      gp sync-await env-setup
      ./install-aws-cli.sh
      gp sync-done aws-cli
  - name: Setup default aws-vault & Open Dashboards
    command: |
      gp sync-await aws-cli
      ./collect-credentials.sh
      ./open-cloud-dashboards.sh
  - name: Install kubectl
    command: source ./install-kubectl.sh
  - name: Install Terraform
    command: source ./install-terraform.sh
  - name: Install Visual Studio Code extensions
    command: source ./install-vsextensions.sh
  - name: Install PostgreSQL
    command: source ./install-postgres.sh
  - name: Install Google Cloud SDK
    command: |
      source ./install-gcloud.sh
      gp sync-done gcloud-setup
vscode:
  extensions:
    - ms-python.python
    - aws-toolkit-vscode.aws-toolkit-vscode
    - ms-mssql.mssql
    - amazon-dynamodb.aws-dynamodb-toolkit
    
github:
  prebuilds:
    master: true
